// PS/2 key events from hps_io (ps2_key) to the codes of an Ampex Dialogue 80's
// keys.  US layout.  Shift, Ctrl and Caps Lock are handled here; keymap.mem
// holds the characters and is generated by tools/py/mk_keymap.py.  CAPS is
// what Caps Lock is after a reset.
//
// A code below 80 hex is a character.  The others are the terminal's own keys,
// with the codes its firmware has for them; they act on the screen and are
// never sent to the computer:
//
//   Left, Right, Up, Down   08 0C 0B 0A, characters like any other
//   Home                    1E
//   Shift+Tab               90  BACK TAB
//   Page Down               8A  PAGE: the next page of display memory
//   Insert                  96  CHAR INS          Shift+Insert   94  LINE INS
//   Shift+Delete            97  CHAR DEL          Ctrl+Delete    95  LINE DEL
//   F4                      B4  SEND LINE         Shift          B6  the protected fields too
//   Ctrl+F4                 B5  SEND PAGE         Ctrl+Shift     B7
//   F5                      8B  CLEAR             Shift          8C  with nulls
//   Ctrl+F5                 82  CTRL+CLEAR: unlocks the keyboard and takes an error message away
//   F6                      94  LINE INS          Shift          95  LINE DEL
//   F7                      96  CHAR INS          Shift          97  CHAR DEL
//   F8                      D4  LINE ERASE        Shift          F4  with nulls
//   Ctrl+F8                 D9  PAGE ERASE        Ctrl+Shift     F9
//   F9                      91  TAB SET           Shift          92  TAB CLEAR
//   Ctrl+Shift+F9           93  all tab stops
//   F10                     85  conversation mode Shift          84  block mode
//   F11                     89  protect mode off  Shift          88  on
//   Ctrl+F11                87  write protect off Ctrl+Shift     86  on
//
// The terminal's PRINT and BREAK keys and its twenty programmable keys have no
// key here.

module term_keyboard #(
	parameter CAPS = 0
) (
	input wire clk,
	input wire reset,

	input wire [10:0] ps2_key,  // [10] toggles per event, [9] pressed, [8] extended, [7:0] code

	output reg  [7:0] dout,
	output reg        dout_valid,
	input  wire       dout_ready
);

	reg [7:0] keymap[0:511];
	initial $readmemh("keymap.mem", keymap);

	reg old_stb;
	reg shift_l, shift_r, ctrl_l, ctrl_r, caps;
	reg       lookup;  // a key press is waiting for the ROM
	reg       lookup_ext;
	reg [7:0] lookup_code;
	reg [8:0] rom_addr;
	reg [7:0] rom_q;
	reg       rom_vld;

	wire       pressed = ps2_key[9];
	wire       ext = ps2_key[8];
	wire [7:0] code = ps2_key[7:0];
	wire       shift = shift_l | shift_r;
	wire       ctrl = ctrl_l | ctrl_r;

	// the keys that are not in the table of characters: the extended ones and
	// the function keys
	reg [7:0] own;
	always @(*) begin
		own = 8'h00;
		if (lookup_ext)
			case (lookup_code)
				8'h5A:   own = 8'h0D;  // keypad Enter
				8'h4A:   own = "/";  // keypad /
				8'h6B:   own = 8'h08;  // Left
				8'h74:   own = 8'h0C;  // Right
				8'h75:   own = 8'h0B;  // Up
				8'h72:   own = 8'h0A;  // Down
				8'h6C:   own = 8'h1E;  // Home
				8'h7A:   own = 8'h8A;  // Page Down
				8'h70:   own = shift ? 8'h94 : 8'h96;  // Insert
				8'h71:   own = shift ? 8'h97 : ctrl ? 8'h95 : 8'h7F;  // Delete
				default: ;
			endcase
		else
			case (lookup_code)
				8'h0D:   if (shift) own = 8'h90;  // Shift+Tab
				8'h0C:   own = ctrl ? (shift ? 8'hB7 : 8'hB5) : (shift ? 8'hB6 : 8'hB4);  // F4
				8'h03:   own = ctrl ? 8'h82 : (shift ? 8'h8C : 8'h8B);  // F5
				8'h0B:   own = shift ? 8'h95 : 8'h94;  // F6
				8'h83:   own = shift ? 8'h97 : 8'h96;  // F7
				8'h0A:   own = ctrl ? (shift ? 8'hF9 : 8'hD9) : (shift ? 8'hF4 : 8'hD4);  // F8
				8'h01:   own = shift ? (ctrl ? 8'h93 : 8'h92) : 8'h91;  // F9
				8'h09:   own = shift ? 8'h84 : 8'h85;  // F10
				8'h78:   own = ctrl ? (shift ? 8'h86 : 8'h87) : (shift ? 8'h88 : 8'h89);  // F11
				default: ;
			endcase
	end

	wire [7:0] base = lookup_ext ? 8'h00 : rom_q;
	wire       is_letter = ((base >= "a") && (base <= "z")) || ((base >= "A") && (base <= "Z"));
	wire [7:0] cased = (caps && is_letter) ? (base ^ 8'h20) : base;
	wire [7:0] typed = (ctrl && (cased >= 8'h40) && (cased <= 8'h7F)) ? (cased & 8'h1F) : cased;
	wire [7:0] key_char = (own != 8'h00) ? own : typed;

	always @(posedge clk) begin
		rom_q   <= keymap[rom_addr];
		rom_vld <= lookup;
		lookup  <= 0;

		if (dout_valid && dout_ready) dout_valid <= 0;

		if (reset) begin
			old_stb    <= ps2_key[10];
			shift_l    <= 0;
			shift_r    <= 0;
			ctrl_l     <= 0;
			ctrl_r     <= 0;
			caps       <= CAPS;
			lookup     <= 0;
			rom_vld    <= 0;
			dout_valid <= 0;
		end else begin
			old_stb <= ps2_key[10];
			if (old_stb != ps2_key[10]) begin
				case ({
					ext, code
				})
					9'h012: shift_l <= pressed;
					9'h059: shift_r <= pressed;
					9'h014: ctrl_l <= pressed;
					9'h114: ctrl_r <= pressed;
					9'h058: if (pressed) caps <= ~caps;
					default:
					if (pressed) begin
						rom_addr    <= {shift, code};
						lookup      <= 1;
						lookup_ext  <= ext;
						lookup_code <= code;
					end
				endcase
			end

			// rom_addr was set two clocks ago, rom_q is valid now
			if (rom_vld && key_char != 0 && !dout_valid) begin
				dout       <= key_char;
				dout_valid <= 1;
			end
		end
	end

endmodule
