// PS/2 key events from hps_io (ps2_key) to ASCII bytes for the Cray console.
// US layout.  Shift, Ctrl and Caps Lock are handled here; keymap.mem holds the
// rest and is generated by tools/py/mk_keymap.py.  CAPS is what Caps Lock is
// after a reset.

module term_keyboard #(
	parameter CAPS = 0
) (
	input wire clk,
	input wire reset,

	input wire [10:0] ps2_key,  // [10] toggles per event, [9] pressed, [8] extended, [7:0] code

	output reg  [7:0] dout,
	output reg        dout_valid,
	input  wire       dout_ready
);

	reg [7:0] keymap[0:511];
	initial $readmemh("keymap.mem", keymap);

	reg old_stb;
	reg shift_l, shift_r, ctrl_l, ctrl_r, caps;
	reg       lookup;  // a key press is waiting for the ROM
	reg       lookup_ext;
	reg [7:0] lookup_code;
	reg [8:0] rom_addr;
	reg [7:0] rom_q;
	reg       rom_vld;

	wire       pressed = ps2_key[9];
	wire       ext = ps2_key[8];
	wire [7:0] code = ps2_key[7:0];
	wire       shift = shift_l | shift_r;
	wire       ctrl = ctrl_l | ctrl_r;

	// extended keys that produce a character
	reg [7:0] ext_char;
	always @(*) begin
		case (lookup_code)
			8'h5A:   ext_char = 8'h0D;  // keypad Enter
			8'h4A:   ext_char = "/";  // keypad /
			8'h71:   ext_char = 8'h7F;  // Delete
			default: ext_char = 8'h00;
		endcase
	end

	wire [7:0] base = lookup_ext ? ext_char : rom_q;
	wire       is_letter = ((base >= "a") && (base <= "z")) || ((base >= "A") && (base <= "Z"));
	wire [7:0] cased = (caps && is_letter) ? (base ^ 8'h20) : base;
	wire [7:0] key_char = (ctrl && (cased >= 8'h40) && (cased <= 8'h7F)) ? (cased & 8'h1F) : cased;

	always @(posedge clk) begin
		rom_q   <= keymap[rom_addr];
		rom_vld <= lookup;
		lookup  <= 0;

		if (dout_valid && dout_ready) dout_valid <= 0;

		if (reset) begin
			old_stb    <= ps2_key[10];
			shift_l    <= 0;
			shift_r    <= 0;
			ctrl_l     <= 0;
			ctrl_r     <= 0;
			caps       <= CAPS;
			lookup     <= 0;
			rom_vld    <= 0;
			dout_valid <= 0;
		end else begin
			old_stb <= ps2_key[10];
			if (old_stb != ps2_key[10]) begin
				case ({
					ext, code
				})
					9'h012: shift_l <= pressed;
					9'h059: shift_r <= pressed;
					9'h014: ctrl_l <= pressed;
					9'h114: ctrl_r <= pressed;
					9'h058: if (pressed) caps <= ~caps;
					default:
					if (pressed) begin
						rom_addr    <= {shift, code};
						lookup      <= 1;
						lookup_ext  <= ext;
						lookup_code <= code;
					end
				endcase
			end

			// rom_addr was set two clocks ago, rom_q is valid now
			if (rom_vld && key_char != 0 && !dout_valid) begin
				dout       <= key_char;
				dout_valid <= 1;
			end
		end
	end

endmodule
