//! Reciprocal approximation unit (instructions 070 and 174).
//!
//! No Cray manual gives this unit at bit level. HR-0097B page 4-33 says only that a table
//! lookup is followed by Newton iterations inside the unit and that the answer is accurate
//! to 30 bits. The bit-level behaviour implemented here was learned from Andras Tantos's
//! cray-sim (`ReciprocApprox` in `cray_float.cpp`), which in turn was reconstructed from the
//! software model of the unit in the Cray X-MP diagnostics. This file is an independent
//! implementation of that behaviour: the lookup values are generated by formula and the
//! truncation pattern of the second multiply is written as a table of dropped bits.
//!
//! The computation, with `B` the 48-bit coefficient treated as a fraction in [1/2, 1):
//!
//! 1. `A0 = round(2^15 / (128.5 + i))` where `i` is coefficient bits 46..40. `A0 / 2^7`
//!    approximates `1/B` to about 8 bits.
//! 2. `A1 = 2*A0 - A0^2 * B` on the upper 24 coefficient bits, with truncated rows, kept to
//!    18 bits.
//! 3. `A2 = 2*A1 - A1^2 * B` on the upper 37 coefficient bits through a truncated multiply
//!    pyramid of its own, kept to 33 bits (the low 15 coefficient bits of the result are
//!    always zero).

use crate::{pack, unpack, FpResult, Profile, EXP_OVERFLOW, NORM_BIT};

/// First approximation for table index `index` (coefficient bits 46..40):
/// `round(2^15 / (128.5 + index))`, an integer in `128..=255`.
///
/// # Panics
/// Panics if `index >= 128`.
pub fn recip_seed(index: u32) -> u32 {
    assert!(index < 128, "reciprocal table index out of range");
    let den = 257 + 2 * index; // 2 * (128.5 + index)
    ((1 << 17) + den) / (2 * den)
}

/// The lookup word as the X-MP diagnostic model (and cray-sim) stores it: `2*A0` in bits
/// 26..18 and `A0^2` in bits 17..2. Only used to show that the formula reproduces that table.
pub fn recip_table_word(index: u32) -> u32 {
    let a0 = recip_seed(index);
    ((2 * a0) << 18) | ((a0 * a0) << 2)
}

/// A row is skipped entirely (bit 2 of `A1^2` takes no part in the multiply).
const SKIP: u8 = 0xFF;

/// Truncation pattern of the `A1^2 * B` multiply. Bit `i` of `A1^2` (bit 0 first) selects a
/// row; the rows are grouped as listed. For each row the value is the number of low-order
/// bits dropped from that row; the second field is the number of low-order bits dropped
/// from the sum of the group.
const SECOND_MULTIPLY: [(&[u8], u8); 7] = [
    (&[2, 2, SKIP, 2, 2, 2, 2, 2], 3),
    (&[1, 0, 0, 0], 2),
    (&[2, 2, 3, 4], 0),
    (&[2, 3, 2, 2, 2, 2, 2, 2], 3),
    (&[1, 0, 0, 0], 2),
    (&[2, 2, 3, 4], 0),
    (&[2, 2, 2, 2], 3),
];

fn clear_low(value: u64, bits: u8) -> u64 {
    value & !((1u64 << bits) - 1)
}

/// The 48-bit result coefficient for input coefficient `coef` (bit 47 is forced in the
/// result; the caller clears it again on a range error).
fn recip_coefficient(coef: u64) -> u64 {
    let a0 = u64::from(recip_seed(((coef >> 40) & 0x7F) as u32));

    // First step. The upper 24 bits are used as given: bit 47 is *not* forced here, which is
    // why an unnormalised operand gives a meaningless result.
    let b24 = coef >> 24;
    let a0_squared = a0 * a0;
    let mut product = 0u64;
    for k in 0..16 {
        if (a0_squared >> k) & 1 != 0 {
            product += b24 >> (15 - k);
        }
    }
    // 2*A0 scaled by 2^16, plus A0 as a rounding term, minus the product; keep 18 bits.
    let a1 = ((a0 * ((1 << 17) + 1)).wrapping_sub(product) >> 6) & 0x3_FFFF;

    // Second step. Here bit 47 is assumed set.
    let b37 = (coef | NORM_BIT) >> 11;
    let wide = b37 << 3;
    let a1_squared = a1 * a1;
    let mut sum = 0u64;
    let mut bit = 0u32;
    for (rows, group_drop) in SECOND_MULTIPLY {
        let mut group = 0u64;
        for &row_drop in rows {
            if row_drop != SKIP && (a1_squared >> bit) & 1 != 0 {
                group += clear_low(wide >> (35 - bit), row_drop);
            }
            bit += 1;
        }
        sum += clear_low(group, group_drop);
    }
    // Round at bit 3, then drop six bits.
    let product = ((sum >> 4) + ((sum >> 3) & 1)) >> 2;

    let a2 = (a1 << 31).wrapping_sub(product << 14).wrapping_sub(1);
    (a2 | NORM_BIT) & 0xFFFF_FFFF_8000
}

/// Floating reciprocal approximation (070).
///
/// The result exponent is `0100001 - e` (octal) for an operand exponent `e` in
/// `020002..=057777`. Any other exponent is a range error: `range_error` is set, the result
/// exponent is `060000` and bit 47 of the computed coefficient is cleared. The sign of the
/// operand is copied to the result in every case.
///
/// The operand is assumed normalised; bit 47 is not tested. [`Profile::Cray1`] returns the
/// same result as [`Profile::Xmp`]: the CRAY-1 manual gives no bit-level description of its
/// reciprocal unit.
pub fn frecip(a: u64, profile: Profile) -> FpResult {
    match profile {
        Profile::Xmp | Profile::Cray1 => {}
    }
    let x = unpack(a);
    let coef = recip_coefficient(x.coef);
    if x.exp <= 0o20001 || x.exp >= EXP_OVERFLOW {
        return FpResult {
            value: pack(x.sign, EXP_OVERFLOW, coef & !NORM_BIT),
            range_error: true,
        };
    }
    FpResult {
        value: pack(x.sign, 0o100001 - x.exp, coef),
        range_error: false,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn seed_endpoints() {
        assert_eq!(recip_seed(0), 255);
        assert_eq!(recip_seed(127), 128);
        assert_eq!(recip_table_word(0), 0x07FB_F804);
        assert_eq!(recip_table_word(127), 0x0401_0000);
    }

    #[test]
    fn second_multiply_covers_36_rows() {
        let rows: usize = SECOND_MULTIPLY.iter().map(|(r, _)| r.len()).sum();
        assert_eq!(rows, 36);
    }

    #[test]
    fn reciprocal_of_one_and_of_zero() {
        // cray-sim fp_test.cpp: 1/1.0 and the range-error result for a zero operand.
        assert_eq!(
            frecip(0x4001_8000_0000_0000, Profile::Xmp).value,
            0x4000_FFFF_FFFF_8000
        );
        let z = frecip(0, Profile::Xmp);
        assert_eq!(z.value, 0x6000_7FFC_02FF_0000);
        assert!(z.range_error);
    }
}
