// The devices of the I/O Subsystem that have times of their own besides the
// disk drives, side by side for sim/harness/times_main.cpp: a console
// (rtl/ios/ios_console.v), the Peripheral Expander (rtl/ios/ios_expander.v)
// and the channel pair to the mainframe (rtl/ios/ios_link.v).
module ios_times_tb (
	input wire clk,
	input wire rst,
	input wire i_real,

	// the console's display channel
	input  wire       c_display,
	input  wire [3:0] c_function,
	input  wire [6:0] c_a,
	output wire       c_busy,
	output wire       c_done,
	output wire       c_char_valid,
	output wire [6:0] c_char,
	input  wire       c_char_ready,

	// the Peripheral Expander
	input  wire        x_strobe,
	input  wire [ 3:0] x_function,
	input  wire [15:0] x_a,
	output wire [15:0] x_data,
	output wire        x_ask,
	output wire        x_dma_req,
	output wire        x_dma_we,
	output wire [15:0] x_dma_addr,
	output wire [15:0] x_dma_wdata,
	input  wire        x_dma_ack,
	input  wire [15:0] x_dma_rdata,
	output wire        x_tape_req,
	output wire [20:0] x_tape_addr,
	input  wire        x_tape_ack,
	input  wire [63:0] x_tape_data,
	input  wire [23:0] x_tape_bytes,
	output wire        x_print_valid,
	output wire [ 7:0] x_print,
	input  wire        x_print_ready,

	// the channel pair
	input  wire        l_in,
	input  wire        l_out,
	input  wire [ 3:0] l_function,
	input  wire [15:0] l_a,
	output wire [ 1:0] l_done,
	output wire        l_dma_req,
	output wire        l_dma_we,
	output wire [15:0] l_dma_addr,
	output wire [15:0] l_dma_wdata,
	input  wire        l_dma_ack,
	input  wire [15:0] l_dma_rdata,
	input  wire        l_cpu_ready,
	input  wire [15:0] l_cpu_parcel,
	output wire        l_cpu_resume,
	input  wire        l_cpu_disconnect,
	output wire        l_ready,
	output wire [15:0] l_parcel,
	input  wire        l_resume,
	output wire        l_disconnect
);

	ios_console console (
		.clk           (clk),
		.rst           (rst),
		.i_real        (i_real),
		.i_keyboard    (1'b0),
		.i_display     (c_display),
		.i_function    (c_function),
		.i_a           (c_a),
		.o_data        (),
		.o_key_done    (),
		.o_display_busy(c_busy),
		.o_display_done(c_done),
		.i_key_valid   (1'b0),
		.i_key         (7'd0),
		.o_key_ready   (),
		.o_char_valid  (c_char_valid),
		.o_char        (c_char),
		.i_char_ready  (c_char_ready)
	);

	ios_expander expander (
		.clk           (clk),
		.rst           (rst),
		.i_real        (i_real),
		.i_strobe      (x_strobe),
		.i_function    (x_function),
		.i_a           (x_a),
		.o_data        (x_data),
		.o_busy        (),
		.o_done        (),
		.o_ask         (x_ask),
		.o_dma_req     (x_dma_req),
		.o_dma_we      (x_dma_we),
		.o_dma_addr    (x_dma_addr),
		.o_dma_wdata   (x_dma_wdata),
		.i_dma_ack     (x_dma_ack),
		.i_dma_rdata   (x_dma_rdata),
		.o_tape_req    (x_tape_req),
		.o_tape_addr   (x_tape_addr),
		.i_tape_ack    (x_tape_ack),
		.i_tape_data   (x_tape_data),
		.i_tape_bytes  (x_tape_bytes),
		.i_tape_locked (1'b1),
		.i_tape_change (1'b0),
		.o_tape_put    (),
		.o_tape_sync   (),
		.o_tape_at     (),
		.o_tape_wdata  (),
		.i_tape_wack   (1'b0),
		.o_sd_lba      (),
		.o_sd_rd       (),
		.o_sd_wr       (),
		.i_sd_ack      (1'b0),
		.i_sd_buff_addr(9'd0),
		.i_sd_buff_dout(8'd0),
		.o_sd_buff_din (),
		.i_sd_buff_wr  (1'b0),
		.o_print_valid (x_print_valid),
		.o_print       (x_print),
		.i_print_ready (x_print_ready)
	);

	ios_link link (
		.clk               (clk),
		.rst               (rst),
		.i_power_on        (rst),
		.i_real            (i_real),
		.i_in              (l_in),
		.i_out             (l_out),
		.i_function        (l_function),
		.i_a               (l_a),
		.o_data            (),
		.o_busy            (),
		.o_done            (l_done),
		.o_dma_req         (l_dma_req),
		.o_dma_we          (l_dma_we),
		.o_dma_addr        (l_dma_addr),
		.o_dma_wdata       (l_dma_wdata),
		.i_dma_ack         (l_dma_ack),
		.i_dma_rdata       (l_dma_rdata),
		.i_ready           (l_cpu_ready),
		.i_parcel          (l_cpu_parcel),
		.o_resume          (l_cpu_resume),
		.i_disconnect      (l_cpu_disconnect),
		.o_ready           (l_ready),
		.o_parcel          (l_parcel),
		.i_resume          (l_resume),
		.o_disconnect      (l_disconnect),
		.o_cpu_master_clear(),
		.o_io_master_clear ()
	);

endmodule
